<a href="https://colab.research.google.com/github/mohammadrezaasadi/AI/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a vector (1D Array)

In [2]:
vector = np.array([18,15,14,19])
print(vector, "" , vector.shape)

[18 15 14 19]  (4,)


In [ ]:
respaed_vector = vector.reshape((4,1))
print(respaed_vector, "" , respaed_vector.shape)

[[1]
 [2]
 [3]
 [4]]  (4, 1)


Creating a Matrix (2D Array)

In [ ]:
matrix = np.array([[15,19,14,16],[13,15,18,19],[15,14,19,17]])
print(matrix, " " , matrix.shape)

[[15 19 14 16]
 [13 15 18 19]
 [15 14 19 17]]   (3, 4)


Creating a tensor (3D Array)

In [ ]:
tensor = np.array([[[15,14,13,14],[15,18,13,17],[15,14,12,17],[15,14,12,19]]])
print(tensor , " " , tensor.shape)

[[[15 14 13 14]
  [15 18 13 17]
  [15 14 12 17]
  [15 14 12 19]]]   (1, 4, 4)


In [10]:
random = np.random.randint(0,100,(2,2))
print(random)

[[17 86]
 [90 49]]
